metadata/unpackaged/objects/Mass_Update__c.object
<CustomObject>
    <fields>
        <fullName>SFDC_Object__c</fullName>
        <label>SFDC Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mass Update</label>
    <nameField>
        <displayFormat>MU{00000000}</displayFormat>
        <label>Mass Update Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/unpackaged/objects/Mass_Update_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Empty__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Empty</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_Value_CBox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Filter Value CBox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Filter_Value_Date_Time__c</fullName>
        <label>Filter Value Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Filter_Value_Date__c</fullName>
        <label>Filter Value Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Filter_Value_Nbr__c</fullName>
        <label>Filter Value Nbr</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Filter_Value__c</fullName>
        <label>Filter Value</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mass_Update__c</fullName>
        <label>Mass Update</label>
        <referenceTo>Mass_Update__c</referenceTo>
        <relationshipLabel>Mass Update Criterias</relationshipLabel>
        <relationshipName>R00N70000002HPIbEAO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>==</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;=</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;=</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>!=</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N70000002HfPiEAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mass Update Criteria</label>
    <nameField>
        <displayFormat>MUC{000000}</displayFormat>
        <label>Mass Update Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Update Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/unpackaged/objects/Mass_Update_Field__c.object
<CustomObject>
    <fields>
        <fullName>Empty__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Empty</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Value_CBox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Field Value CBox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Value_Date__c</fullName>
        <label>Field Value Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Field_Value_Datetime__c</fullName>
        <label>Field Value Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Field_Value_Nbr__c</fullName>
        <label>Field Value Nbr</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field_Value_Txt_Area__c</fullName>
        <label>Field Value Txt Area</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Field_Value__c</fullName>
        <label>Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mass_Update__c</fullName>
        <label>Mass Update</label>
        <referenceTo>Mass_Update__c</referenceTo>
        <relationshipLabel>Mass Update Fields</relationshipLabel>
        <relationshipName>R00N70000002HPIREA4</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N70000002HfP4EAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mass Update Field</label>
    <nameField>
        <displayFormat>FLD{0000000}</displayFormat>
        <label>Mass Update Fields  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Update Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/unpackaged/classes/MassUpdateUtils.cls
public class MassUpdateUtils {
	public static String createSoql(String operation,Integer recLimit,
									Mass_Update__c massUpdate,
									List<Mass_Update_Field__c> fldsToUpdt,
									List<Mass_Update_Criteria__c> filterCriteria){
		
		String soql = 'select ';
		if(operation == 'UPDATE'){
			soql +=' Id,';	
			if(fldsToUpdt != null){
				for(Mass_Update_Field__c fld : fldsToUpdt){
					soql+= fld.Field_API_Name__c +',';
						
				}
			}
			soql = soql.substring(0,soql.length()-1);
		}	
		if(operation == 'COUNT'){
			soql += 'count()';
		}	
		soql += ' from '+massUpdate.SFDC_Object__c;

		if(filterCriteria != null && filterCriteria.size() > 0){
			soql += ' where ';
			Integer currIndex =0;
			for(Mass_Update_Criteria__c crit : filterCriteria){
				if(crit.Empty__c){
					soql+= crit.Field_API_Name__c+crit.Operator__c+'null';	
				}else{
					if(crit.Operator__c == 'NOT IN' || crit.Operator__c == 'IN'){
						soql+= crit.Field_API_Name__c +' '+crit.Operator__c+' (';
						soql+= crit.Filter_Value__c;
						soql+= ')';	
					}else{
						soql+= crit.Field_API_Name__c +' '+crit.Operator__c;
						if(crit.Filter_Value__c != null){
							soql+= crit.Filter_Value__c;
						}else if(crit.Filter_Value_Date__c !=null){
							soql+= getFormattedDate(crit.Filter_Value_Date__c);
						}else if(crit.Filter_Value_Date_Time__c !=null){
							soql+= getFormattedDate(crit.Filter_Value_Date_Time__c);
						}else if(crit.Filter_Value_Nbr__c !=null){
							soql+= crit.Filter_Value_Nbr__c;
						}else if(crit.User__c != null){
							soql+= '\''+crit.User__c+'\'';
						}else if(crit.Filter_Value_CBox__c !=null){
							soql+= crit.Filter_Value_CBox__c;
						}
					}
				}				
				currIndex++;
				if(currIndex !=filterCriteria.size()){
					soql +=' and ';	
				} 
			}	
		}	
		if(	operation != 'COUNT'){
			soql +=' LIMIT '+recLimit;
		}
		System.debug('>>>>>>>>>>>>>> SOQL ='+soql);
		return soql;
	}

	public static String updateRecords(	Mass_Update__c massUpdate,
										List<Mass_Update_Field__c> fldsToUpdt,
										List<Mass_Update_Criteria__c> filterCriteria,
										Integer recLimit,
										Boolean shouldRollBack){
		String soql = createSoql('UPDATE',1,massUpdate,fldsToUpdt,filterCriteria);
		List<SObject> objToUpdate = Database.query(soql);
		objToUpdate.clear();
		Savepoint svPoint;
		if(shouldRollBack){
			svPoint = Database.setSavePoint();
		}
		soql = createSoql('UPDATE',recLimit,massUpdate,fldsToUpdt,filterCriteria);
		try{
			Object fldValue;
			for(SObject obj : Database.query(soql)){
				for(Mass_Update_Field__c fld: fldsToUpdt){
					System.debug('>>>>>>>>> fld:'+fld);
					if(fld.Empty__c){
						obj.put(fld.Field_API_Name__c,null);
					}else{
						if (fld.Field_Value__c != null){
							fldValue = fld.Field_Value__c;
						}else if(fld.Field_Value_Date__c !=null){
							fldValue = fld.Field_Value_Date__c;
						}else if(fld.Field_Value_Datetime__c !=null){
							fldValue = fld.Field_Value_Datetime__c;
						}else if(fld.Field_Value_Nbr__c !=null){
							fldValue = fld.Field_Value_Nbr__c;
						}else if(fld.User__c != null){
							fldValue = fld.User__c;
						}else if(fld.Field_Value_Txt_Area__c != null){
							fldValue = fld.Field_Value_Txt_Area__c;
						}else if(fld.User__c != null){
							fldValue = fld.User__c;
						}else if(fld.Field_Value_CBox__c != null){
							fldValue = fld.Field_Value_CBox__c;
						}
						System.debug('Field:'+fld.Field_API_Name__c+',Value='+fldValue);
						obj.put(fld.Field_API_Name__c,fldValue);
					}
				}
				if(objToUpdate.size() == 1000){
					update objToUpdate;
					objToUpdate.clear();
					//objToUpdate = new List<SObject>();
				}else{
					objToUpdate.add(obj);
				}
			}
			update objToUpdate;
			if(shouldRollBack){
				Database.rollback(svPoint);
			}
			
			return 'Update successful!!!';
		}catch(Exception ex){
			return 'Update FAILED.Failure Reason:'+ex.getMessage();
		}									
	}
	
	private static String getFormattedDate(Date dtValue){
		Datetime dtTime = DateTime.newInstance(dtValue.year(),dtValue.month(),dtValue.day());
		return dtTime.format('yyyy-MM-dd');	
	}
	private static String getFormattedDate(DateTime dtValue){
		Datetime dtTime = DateTime.newInstance(dtValue.year(),dtValue.month(),dtValue.day());
		return dtTime.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');	
	}	
	
	public static String getSampleData(Mass_Update__c massUpdate,
										List<Mass_Update_Field__c> fldsToUpdt,
										List<Mass_Update_Criteria__c> filterCriteria,
										Integer recLimit){
		String soql = createSoql('UPDATE',recLimit,massUpdate,fldsToUpdt,filterCriteria);
		GoogleViz gv = new GoogleViz();
      	gv.cols = new List<GoogleViz.col>();
      	Integer colCount=1;
      	gv.cols.add(new GoogleViz.Col('col'+colCount,'Id','t'));
      	for(Mass_Update_Field__c fld: fldsToUpdt){
			
			gv.cols.add(new GoogleViz.Col('col'+colCount,fld.Field_API_Name__c,'t'));
			colCount++;
      	}
      	GoogleViz.row r; 
      	Object fldVal;
		for(SObject obj: Database.query(soql)){
			r = new GoogleViz.row();
			r.cells.add ( new GoogleViz.cell(''+obj.Id));
			for(Mass_Update_Field__c fld: fldsToUpdt){
				fldVal = obj.get(fld.Field_API_Name__c);
				if(fldVal != null){
					r.cells.add ( new GoogleViz.cell(''+fldVal));
				}else{
					r.cells.add ( new GoogleViz.cell('null'));
				}
			}
			gv.addRow( r );
		}
		
		return gv.toJsonString();
		
	}

}